### ISSUE TITLE
这个和ChinaDNS的区别是什么？除过支持ECS之外还有什么新特性么？

### ISSUE THREAD

**Issue by cokebar** [GangZhuo/CleanDNS#1]
Thanks。

**Comment by GangZhuo** [comment]
没有新特性，本来计划国外的网站解析到离 SS 服务器最近的 IP ，国内网站解析到离自己最近的服务器。不过通过维护一个单独的域名列表的方式可能会更好。

Cokebar Chi <notifications@github.com>于2017年6月6日周二 下午7:38写道：

**Comment by cjjdaq** [comment]
思路，也是目前自己想找的dns
主从dns（同时支持设置多上游，ecs client ip）
主DNS：119.29.29.29,119.28.28.28  ecs_ip:自己的公网ip
从DNS：8.8.8.8,8.8.4.4   ecs_ip:自己的ss的ip
hosts列表,匹配直接返回ip
gfwlist列表，匹配直接使用从dns解析。
黑白名单：
白名单命中直接主dns解析，返回ip
黑名单命中直接从dns解析，返回ip
剩下的：
先向主dns发送请求解析，返回的ip如果匹配chnroute.txt直接返回ip，如果不匹配使用从dns解析，并返回ip

**Comment by pexcn** [comment]
看到了似乎使用了红黑树之类的东西，效率是比 ChinaDNS 更高效吗？
