### ISSUE TITLE
可以 release 一个新版本吗？

### ISSUE THREAD

**Issue by pexcn** [GangZhuo/CleanDNS#11]
0.4.1 后面有太多的更新了

顺便一提：[cleandns.config#L2](https://github.com/GangZhuo/CleanDNS/blob/master/openwrt/files/cleandns.config#L2) 这里希望可以改成
```patch
-config cfg
+config cleandns
```
因为看了 openwrt 其它的配置，感觉改成这个更合适。
本来想提交个patch的，但是不会C, 不清楚这里怎么改 [cleandns.c#L1943](https://github.com/GangZhuo/CleanDNS/blob/master/src/cleandns.c#L1943)

**Comment by GangZhuo** [comment]
版本已经发布。另外，config 不计划修改，保持原样的话，UCI 配置看起来是 cleandns.cfg.xxx，修改后 变为 cleandns.cleandns.xxx 有点奇怪。
