### ISSUE TITLE
proxy 选项不能正常工作？

### ISSUE THREAD

**Issue by pexcn** [GangZhuo/CleanDNS#13]
`socks5://127.0.0.1:1080` 是 ss-local 提供的，这是我的配置：
![1](https://user-images.githubusercontent.com/4590439/62762296-5ccb7880-babb-11e9-97dd-88516f74dc45.png)
![2](https://user-images.githubusercontent.com/4590439/62762298-5d640f00-babb-11e9-8369-b76903c302b2.png)

日志里总是显示 timeout, 而且 dig 也无法得到结果。

**Comment by GangZhuo** [comment]
dns server 使用的是 UDP，请确认下代理支持 UDP。或者 dns_server 换用 tcp 模式：tcp://8.8.8.8:53。

**Comment by pexcn** [comment]
`tcp://8.8.8.8:53` 也试过了，还是不行，路由器的 shadowsocks 代理我在 luci 界面开启了 “代理自身”，请问跟这个有关系吗？会不会导致死循环之类的...？

**Comment by pexcn** [comment]
顺便一提，好像有个小问题：我的国内 IP 和国外 IP 分别填的是中国大陆和美国洛杉矶，测试了其它网站都没有问题，但是测试 facebook 的时候不知道为什么会返回距离中国大陆位置近的 IP
```bash
C:\Users\Administrator>dig www.facebook.com @192.168.1.1 -p 5354

; <<>> DiG 9.14.1 <<>> www.facebook.com @192.168.1.1 -p 5354
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 61156
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
; CLIENT-SUBNET: <洛杉矶 VPS 的 IP>/24/0
;; QUESTION SECTION:
;www.facebook.com.              IN      A

;; ANSWER SECTION:
www.facebook.com.       3497    IN      CNAME   star-mini.c10r.facebook.com.
star-mini.c10r.facebook.com. 7  IN      A       31.13.95.36

;; Query time: 16 msec
;; SERVER: 192.168.1.1#5354(192.168.1.1)
;; WHEN: Fri Aug 09 21:21:11 中国标准时间 2019
;; MSG SIZE  rcvd: 156
```
返回的结果 `31.13.95.36` 是 facebook 香港 CDN 的 IP, 为什么不是接近洛杉矶的 CDN IP?

**Comment by GangZhuo** [comment]
不确定是不是代理自身的问题，可以关闭试试。

第 2 个问题，未测试，不过有可能：
1. 规则是：有国内 IP 的，优先选择国内 IP
2. 有时候虽然设置了 ECS，谷歌服务器返回的却不是离它最近的 IP，这可能和 DNS 解析配置有关系。
