### ISSUE TITLE
现在的版本 (0.3.1) 必须要设置两个上游吗？

### ISSUE THREAD

**Issue by pexcn** [GangZhuo/CleanDNS#6]
请问 `-s` 参数必须设置一个国内 DNS, 一个国外 DNS 吗？
我现在的设置是 `... -s 127.0.0.1:5300 ...`, 127.0.0.1:5300 是通过 shadowsocks-libev 的 ss-tunnel 端口转发 8.8.8.8:53, 请问这样设置可以吗？

**Comment by GangZhuo** [comment]
设置一个就行了

**Comment by pexcn** [comment]
想问下现在的具体逻辑是怎样的，我看到了最近的更新好像挺大的。
现在是总是返回距离用户地理位置近的 IP 吗？

我现在仍然遇到了这样的问题（下面是我的 config）：
```cfg
config cfg
        option bind_addr '127.0.0.1'
        option bind_port '5301'
        option chnroute '/etc/chinadns_chnroute.txt'
        option china_ip '<深圳 IP>/24'
        option foreign_ip '<新加坡 IP>/24'
        option dns_server '127.0.0.1:5300 (ss-tunnel 转发 的 8.8.8.8:53)'
        option compression '1'
        option pid_file '/var/run/cleandns.pid'
```

`127.0.0.1:5301` 是作为 ChinaDNS 后端的可信 IP (国外 IP), 我通过了 dig 测试了以下域名：
```bash
# 都是 dig 路由器的 dnsmasq 53 端口
dig baidu.com # 返回正确，距离深圳位置近的国内 IP
dig www.baidu.com # 返回异常，返回了香港 IP, 导致 shadowsocks 走了代理
dig 163.com # 返回正确，距离深圳位置近的国内 IP
dig www.163.com # 返回异常，返回了香港 IP, 导致 shadowsocks 走了代理
```
能不能让他过滤掉境外的 IP?

**Comment by pexcn** [comment]
> 设置一个就行了

我又测试了，当设置两个上游，一个 `8.8.8.8:53`, 一个 `114.114.114.114:53` 的时候，dig 以下域名，结果都正常，这是为什么呢？
```bash
dig baidu.com
dig www.baidu.com
dig 163.com
dig www.163.com
```

**Comment by GangZhuo** [comment]
规则就是：

1) 结果中包含国内 IP，则
      a) 是通过国内子网解析的，则得 10 分，否则得 5 分；
      b) 是国内 DNS 服务器返回的，则得 20 分，否则得 10 分。

2) 结果不包含国内 IP，则
      a) 是通过国外子网解析的，则得 4 分，否则得 2 分；
      b) 是国外 DNS 服务器返回的，则得 10 分，否则得 5 分。

最终分高者作为最终结果。参考 https://github.com/GangZhuo/CleanDNS/blob/master/src/cleandns.c#L723 。

大体上就是：

    1) 如果解析结果中有包含中国 IP ，则优先选择，如果多个解析结果都包含中国 IP，则国内 DNS 服务器解析的结果优先，再然后就是 ECS 使用国内子网的优先。
    2) 如果所有的解析结果都仅包含国外 IP，则优先选国外 DNS 服务器的解析结果，然后是 ECS 使用国外子网的优先。

使用时，不需要 ChinaDNS ，直接作为 dnsmasq 的上游就行了。
配置时，国内的 DNS 服务不需要支持 ECS。

**Comment by GangZhuo** [comment]
另外，测试下来，国外 DNS 服务器使用 8.8.8.8 时，不需要走代理，也能获得正确的结果。参考 https://github.com/GangZhuo/CleanDNS/wiki/%E8%BE%83%E7%B2%BE%E5%87%86%E7%9A%84%E8%BF%87%E6%BB%A4-8.8.8.8-%E6%B1%A1%E6%9F%93%E7%9A%84%E5%8A%9E%E6%B3%95 。搜索了下，网上之前也有人提到过这个方法。

**Comment by pexcn** [comment]
感谢解答，我的还有个疑问是：
如这里所说的 https://github.com/GangZhuo/CleanDNS/issues/6#issuecomment-482939070 ，当我通过 ss-tunnel 转发 8.8.8.8:53 到 127.0.0.1:5300 时，为什么得到的结果会有香港 IP？是不是 8.8.8.8 把我判断为我的位置在新加坡呢？

**Comment by GangZhuo** [comment]
这个不知道了。你运行 cleaners 时可以多加几个 -v 参数（最多三个），这样可以打印出 cleandns 收到的所有解析结果，可以看看是不是还有更优解。 

cleandns 会等待所有的解析结果到达后才会判断最优解，如果超时时间到达后还有结果未收到，则在已收到的结果中选最优解。

你这种情况有可能是更好的结果还没收到，超时时间就已经到达了。

**Comment by pexcn** [comment]
嗯，非常感谢。
我测了几次，看起来像是对 8.8.8.8 请求的 IP 的问题。
如果我不用 ss-tunnel 或者 iptables 端口转发，那么解析的结果是正常的（尽管偶尔会有污染）；
如果用了端口转发，那么解析的结果则是距离端口转发的机器位置较近的 IP.

问题转到：https://github.com/GangZhuo/CleanDNS/issues/7
